[package]
name = "zkedit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.40"
structopt = { version = "0.3.26", default-features = false }
image = "0.24.5"
zkedit-zkp = { path = "../zkp" }